#!/bin/bash

VERSION=$(docker run --rm -i $DOCKER_REPO:latest --version | head -1 | cut -d ' ' -f 2)
echo "VERSION: $VERSION"

docker tag $DOCKER_REPO:latest $DOCKER_REPO:$VERSION
docker push $DOCKER_REPO:$VERSION
